In [1]:
import numpy as np 

li = []
size = int(input("Enter size of Array : "))

for i in range(size):
    val = int(input("Enter size of Array : "))
    li.append(val)
arr = np.array(li)
print(arr)

Enter size of Array : 2
Enter size of Array : 1
Enter size of Array : 2
[1 2]


# How to check shape and size of an array?


In [2]:
print(arr.size, arr.shape)

2 (2,)


In [3]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print("Total Shape = ",b.shape)
print("Total Element = ", b.size)

Total Shape =  (3, 3)
Total Element =  9


In [5]:
'''
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

c1 = [1,4,7]
c2 = [2,5,8]
c3 = [3,6,9]
'''

'\nr1 = [1,2,3]\nr2 = [4,5,6]\nr3 = [7,8,9]\n\nc1 = [1,4,7]\nc2 = [2,5,8]\nc3 = [3,6,9]\n'

In [6]:
#Image ===> pixels ===> (0-255)px ===> 0px (complete black), 255px
#convert ===> grayscale Image ===>
# Image(Pixels) ===> Normalization(0-1) ===> 0px black, 1px white

# 0, 1 ===> Neoron System

#Matrix ===> rows, columns
#Symmetric Matrix ===> n(rows) = n(colemns)
#Asymmetric Matrix ===> n(rows) != n(columns)
#Diagonal Elements = [(1,1), (2,2), (3,3)]


# (1). zeros ===> It will crate an array in which all the elements are zero.

In [7]:
a= np.zeros(4)
a

array([0., 0., 0., 0.])

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# (2). ones() ===> It will crate an array in which all the elements are one.

In [9]:
a = np.ones(3)
a

array([1., 1., 1.])

In [10]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# (3). eye() ===> This function will create an array with diagonal values as 1s and rest all are 0s

In [11]:
a = np.eye(3,4) #Asymmetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
a = np.eye(4) #Symmetric  Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# (4). Diag ==> this function creates a two dimensional array with all the diagonal element as the given value and rest are zeros

In [ ]:
import numpy as np
a = np.diag([1,4,8,9])
a

# (5). randint ==> this function is used to generate a random number between a given range.

syntax == randint(min_value, max_value, totalnumber)

In [150]:
import numpy as np
a = np.random.randint(1,10,3)
a

array([4, 9, 9])

# (6). This fuinction is used to generate a random number between 0 to 1.

Syntax  == rand(number of values)

In [152]:
import numpy as np
a = np.random.rand(5)
a

array([0.33280052, 0.04056838, 0.08697335, 0.53851381, 0.11420798])

# (7). randn() ==> This function is used to generate a random a number from -3 to 3. This may return postive or negative number as well.

Syntax ==> random.randn(number of values)

In [153]:
import numpy as np
a = np.random.randn(5)
a


array([-1.5176228 ,  0.47710984, -0.04608321,  1.30848684, -0.62414256])

# Reshpaing data

In [156]:
import numpy as np
a =np.random.randint(0,50,12)
a

array([22, 26, 33, 48, 18, 32, 38, 44, 16, 47, 20, 29])

# n(rows)*n(columns) = n(total_elements)

In [157]:
a.shape

(12,)

In [158]:
a = a.reshape(2,6)
a

array([[22, 26, 33, 48, 18, 32],
       [38, 44, 16, 47, 20, 29]])

In [159]:
a = a.reshape(3,4)
a

array([[22, 26, 33, 48],
       [18, 32, 38, 44],
       [16, 47, 20, 29]])

In [160]:
a = a.reshape(4,3)
a

array([[22, 26, 33],
       [48, 18, 32],
       [38, 44, 16],
       [47, 20, 29]])

In [161]:
a = a.reshape(6,2)
a

array([[22, 26],
       [33, 48],
       [18, 32],
       [38, 44],
       [16, 47],
       [20, 29]])

In [164]:
a = a.reshape(12,1)
a

array([[22],
       [26],
       [33],
       [48],
       [18],
       [32],
       [38],
       [44],
       [16],
       [47],
       [20],
       [29]])

# Q : for 64 `

In [167]:
import numpy as np
a =np.random.randint(0,100,64)
a

array([51, 39, 56, 30,  9, 12, 99, 28, 18, 97, 14, 86,  2, 39, 13,  8, 10,
       56, 19, 10,  6, 64, 32, 20, 44, 88, 97, 29, 80, 21, 67, 84, 78, 45,
       12, 81, 79, 21, 91, 30, 54, 65, 11, 64, 35, 88, 23, 26, 92, 80, 71,
       86, 57, 64, 60, 80, 42, 73,  2, 24, 94, 42, 67, 48])

In [168]:
a = a.reshape(1,64)
a

array([[51, 39, 56, 30,  9, 12, 99, 28, 18, 97, 14, 86,  2, 39, 13,  8,
        10, 56, 19, 10,  6, 64, 32, 20, 44, 88, 97, 29, 80, 21, 67, 84,
        78, 45, 12, 81, 79, 21, 91, 30, 54, 65, 11, 64, 35, 88, 23, 26,
        92, 80, 71, 86, 57, 64, 60, 80, 42, 73,  2, 24, 94, 42, 67, 48]])

In [169]:
a = a.reshape(2,32)
a

array([[51, 39, 56, 30,  9, 12, 99, 28, 18, 97, 14, 86,  2, 39, 13,  8,
        10, 56, 19, 10,  6, 64, 32, 20, 44, 88, 97, 29, 80, 21, 67, 84],
       [78, 45, 12, 81, 79, 21, 91, 30, 54, 65, 11, 64, 35, 88, 23, 26,
        92, 80, 71, 86, 57, 64, 60, 80, 42, 73,  2, 24, 94, 42, 67, 48]])

In [170]:
a = a.reshape(4,16)
a

array([[51, 39, 56, 30,  9, 12, 99, 28, 18, 97, 14, 86,  2, 39, 13,  8],
       [10, 56, 19, 10,  6, 64, 32, 20, 44, 88, 97, 29, 80, 21, 67, 84],
       [78, 45, 12, 81, 79, 21, 91, 30, 54, 65, 11, 64, 35, 88, 23, 26],
       [92, 80, 71, 86, 57, 64, 60, 80, 42, 73,  2, 24, 94, 42, 67, 48]])

In [171]:
a = a.reshape(8,8)
a

array([[51, 39, 56, 30,  9, 12, 99, 28],
       [18, 97, 14, 86,  2, 39, 13,  8],
       [10, 56, 19, 10,  6, 64, 32, 20],
       [44, 88, 97, 29, 80, 21, 67, 84],
       [78, 45, 12, 81, 79, 21, 91, 30],
       [54, 65, 11, 64, 35, 88, 23, 26],
       [92, 80, 71, 86, 57, 64, 60, 80],
       [42, 73,  2, 24, 94, 42, 67, 48]])

In [172]:
a = a.reshape(16,4)
a

array([[51, 39, 56, 30],
       [ 9, 12, 99, 28],
       [18, 97, 14, 86],
       [ 2, 39, 13,  8],
       [10, 56, 19, 10],
       [ 6, 64, 32, 20],
       [44, 88, 97, 29],
       [80, 21, 67, 84],
       [78, 45, 12, 81],
       [79, 21, 91, 30],
       [54, 65, 11, 64],
       [35, 88, 23, 26],
       [92, 80, 71, 86],
       [57, 64, 60, 80],
       [42, 73,  2, 24],
       [94, 42, 67, 48]])

In [173]:
a = a.reshape(32,2)
a

array([[51, 39],
       [56, 30],
       [ 9, 12],
       [99, 28],
       [18, 97],
       [14, 86],
       [ 2, 39],
       [13,  8],
       [10, 56],
       [19, 10],
       [ 6, 64],
       [32, 20],
       [44, 88],
       [97, 29],
       [80, 21],
       [67, 84],
       [78, 45],
       [12, 81],
       [79, 21],
       [91, 30],
       [54, 65],
       [11, 64],
       [35, 88],
       [23, 26],
       [92, 80],
       [71, 86],
       [57, 64],
       [60, 80],
       [42, 73],
       [ 2, 24],
       [94, 42],
       [67, 48]])

In [174]:
a = a.reshape(64,1)
a

array([[51],
       [39],
       [56],
       [30],
       [ 9],
       [12],
       [99],
       [28],
       [18],
       [97],
       [14],
       [86],
       [ 2],
       [39],
       [13],
       [ 8],
       [10],
       [56],
       [19],
       [10],
       [ 6],
       [64],
       [32],
       [20],
       [44],
       [88],
       [97],
       [29],
       [80],
       [21],
       [67],
       [84],
       [78],
       [45],
       [12],
       [81],
       [79],
       [21],
       [91],
       [30],
       [54],
       [65],
       [11],
       [64],
       [35],
       [88],
       [23],
       [26],
       [92],
       [80],
       [71],
       [86],
       [57],
       [64],
       [60],
       [80],
       [42],
       [73],
       [ 2],
       [24],
       [94],
       [42],
       [67],
       [48]])

# Principle of -1

In [175]:
a.reshape(-1,4)

array([[51, 39, 56, 30],
       [ 9, 12, 99, 28],
       [18, 97, 14, 86],
       [ 2, 39, 13,  8],
       [10, 56, 19, 10],
       [ 6, 64, 32, 20],
       [44, 88, 97, 29],
       [80, 21, 67, 84],
       [78, 45, 12, 81],
       [79, 21, 91, 30],
       [54, 65, 11, 64],
       [35, 88, 23, 26],
       [92, 80, 71, 86],
       [57, 64, 60, 80],
       [42, 73,  2, 24],
       [94, 42, 67, 48]])

# seed function() ==> We know that randint function generates random numbers. Everytime we run the program, new set of random number is genrated. So, solve this problem we will use seed function.


In [219]:
import numpy as np
a= np.random.randint(1,100,10)
np.random.seed(1)
a

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

## View vs Copy ==> When we slice a sub-array from an array, It may be done by two ways.


## View

In [221]:
import numpy as np
a = np.array([12,12,53,23,24,13,4,32])
b = a[3:5]
b[:] = 0
a

array([12, 12, 53,  0,  0, 13,  4, 32])

## Copy

In [222]:
a = np.array([12,12,53,23,24,13,4,32])
b = a[3:5].copy()
b[:] = 0
a

array([12, 12, 53, 23, 24, 13,  4, 32])

## conditional selection

In [224]:
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [225]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [226]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [228]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [229]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

## Operations on Array

In [230]:
import numpy as np
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [231]:
a+2

array([3, 4, 5, 6])

In [232]:
a**2

array([ 1,  4,  9, 16])

In [234]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [237]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [238]:
a+b

array([[ 6,  8],
       [10, 12]])

In [239]:
b-a

array([[4, 4],
       [4, 4]])

In [241]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [243]:
b*a

array([[ 5, 12],
       [21, 32]])

In [240]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [244]:
import numpy as np
a = np.array([10,20,30,40,50])
np.min(a)

10

In [246]:
np.max(a)

50

In [247]:
np.argmin(a)

0

In [248]:
np.argmax(a)

4

In [249]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [250]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

## Linspace() ==> This function returns value between a given range and with a same gap between consecutive elements.


In [252]:
import numpy as np
a= np.linspace(1,2,5)
a


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## np.unique(arr,return_index = True, return_count = True)

returns 3 array ==> 1.the array contain unique values. 2. The array with respective index values. 3. The array with counting of frequency of each element.

In [254]:
a = np.array([10,20,30,40,50])
np.unique(a,True,True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([0, 1, 2, 3, 4], dtype=int64))

## Horizontal and verticle stacking

In [256]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [257]:
b

array([5, 6, 7, 8])

In [258]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [259]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])