# 4.) diag ==> this fucnction  create a 2d array with all the diagonal elements as the given valuesa nd rest all zeors


In [1]:
import numpy as np
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 5.) radint==> this function is used to generate a random no. between a given range

# syntax ==> randint(min_value, max_valu, total no)

In [11]:
import numpy as np
a=np.random.randint(1,1000,19)
a

array([868, 414,  19, 826, 995,  83, 635, 205, 695, 754, 351, 116, 905,
       878, 302, 182, 400, 696, 368])

# 6.) rand() ===> this function is used to generate a random no between 0 to 1

# syntax ==> rand(no of values)


In [6]:
import numpy as np
a=np.random.rand(12)
a

array([0.52492602, 0.70696836, 0.19038766, 0.30552767, 0.20272697,
       0.05222519, 0.88181996, 0.22870932, 0.95200426, 0.00100797,
       0.54266233, 0.21615646])

# 7.) randn() ==> this function is used to generate a random no betwneen -3 to +3
# syntax== random.randn(no of values)

In [10]:
import numpy as np
a=np.random.randn(5)
a


array([ 1.06917094, -0.96856285, -0.83163811, -0.54895761, -0.39166663])

In [12]:
# reshaping data

In [13]:
import numpy as np
a=np.random.randint(1,24,12)
a

array([15,  4,  9, 22, 16, 15, 11, 23,  7,  5,  5,  6])

In [15]:
a.shape

(12,)

In [16]:
# n(rows) *n(column)==> n(total elements)


In [17]:
a=a.reshape(2,6)
a

array([[15,  4,  9, 22, 16, 15],
       [11, 23,  7,  5,  5,  6]])

In [18]:
import numpy as np
a=np.random.randint(1,100,64)
a


array([60, 83,  7, 20,  9, 50, 67, 45, 88, 41, 12, 56, 53, 44, 78,  3, 59,
       94, 50, 22, 78,  9, 44,  9, 88, 20, 62, 12, 21, 30, 92, 56,  9, 67,
       64, 38, 75, 66, 53,  6, 61, 68, 61, 74,  5, 78, 35, 34, 55, 23,  9,
       23, 44, 15, 39, 25, 18, 50, 18, 89, 72, 33, 18,  5])

In [19]:
a=a.reshape(2,32)
a


array([[60, 83,  7, 20,  9, 50, 67, 45, 88, 41, 12, 56, 53, 44, 78,  3,
        59, 94, 50, 22, 78,  9, 44,  9, 88, 20, 62, 12, 21, 30, 92, 56],
       [ 9, 67, 64, 38, 75, 66, 53,  6, 61, 68, 61, 74,  5, 78, 35, 34,
        55, 23,  9, 23, 44, 15, 39, 25, 18, 50, 18, 89, 72, 33, 18,  5]])

In [21]:
a=a.reshape(32,2)
a

array([[60, 83],
       [ 7, 20],
       [ 9, 50],
       [67, 45],
       [88, 41],
       [12, 56],
       [53, 44],
       [78,  3],
       [59, 94],
       [50, 22],
       [78,  9],
       [44,  9],
       [88, 20],
       [62, 12],
       [21, 30],
       [92, 56],
       [ 9, 67],
       [64, 38],
       [75, 66],
       [53,  6],
       [61, 68],
       [61, 74],
       [ 5, 78],
       [35, 34],
       [55, 23],
       [ 9, 23],
       [44, 15],
       [39, 25],
       [18, 50],
       [18, 89],
       [72, 33],
       [18,  5]])

In [29]:
a=a.reshape(4,16)
a

array([[60, 83,  7, 20,  9, 50, 67, 45, 88, 41, 12, 56, 53, 44, 78,  3],
       [59, 94, 50, 22, 78,  9, 44,  9, 88, 20, 62, 12, 21, 30, 92, 56],
       [ 9, 67, 64, 38, 75, 66, 53,  6, 61, 68, 61, 74,  5, 78, 35, 34],
       [55, 23,  9, 23, 44, 15, 39, 25, 18, 50, 18, 89, 72, 33, 18,  5]])

# principal of -1

In [27]:
# if no of rows and element are given then we can find no of column by putting -1 in palce of column and viceversa

In [31]:

a=a.reshape(-1,16)
a


array([[60, 83,  7, 20,  9, 50, 67, 45, 88, 41, 12, 56, 53, 44, 78,  3],
       [59, 94, 50, 22, 78,  9, 44,  9, 88, 20, 62, 12, 21, 30, 92, 56],
       [ 9, 67, 64, 38, 75, 66, 53,  6, 61, 68, 61, 74,  5, 78, 35, 34],
       [55, 23,  9, 23, 44, 15, 39, 25, 18, 50, 18, 89, 72, 33, 18,  5]])

# seed ()==> we know that ranint function generates random no everytime we run the program , new set of random no is generated . so , solvethis problem using sheed f unction`1

In [38]:
import numpy as np
np.random.seed(9) # any no can be passed no use of this no 
a=np.random.randint(1,50,6) # after using seed function when we refresh the nos will not update
a

array([29, 23,  2, 23, 41, 28])

# view vs copy ==> when we slice a sub array from an array , it may be done by two ways

In [41]:
# view
import numpy as np
a=np.array([10,20,95,54,78,55,89,65,55])
b=a[3:6]
b[:]=0
a

array([10, 20, 95,  0,  0,  0, 89, 65, 55])

In [48]:
#copy
a=np.array([10,20,95,54,78,55,89,65,55])
b=a[3:6].copy()
b[:]=0
print(a)
print(b)

[10 20 95 54 78 55 89 65 55]
[0 0 0]


# conditional selection

In [50]:
import numpy as np
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [52]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [53]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [54]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

# operations in array

In [58]:
import numpy as np
a=np.array([10,20,95,54,78,55,89,65,55])
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [59]:
a+2

array([3, 4, 5, 6])

In [60]:
a**2

array([ 1,  4,  9, 16])

In [61]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [62]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [63]:
a+b

array([[ 6,  8],
       [10, 12]])

In [64]:
a-b

array([[-4, -4],
       [-4, -4]])

In [66]:
a.dot(b) #matrix multiplication

array([[19, 22],
       [43, 50]])

# some impportant function in numpy

In [67]:
import numpy as np
a=np.array([10,20,30,40])
np.min(a)

10

In [68]:
np.max(a)

40

In [69]:
np.argmin(a) # index of min

0

In [71]:
np.argmax(a)# index of max

3

In [72]:
np.sqrt(a) # squareroot

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [73]:
np.sin(a) # sin value

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

# linspace ==> this function returns values between a guven rangwe and with a same  gap between consecutive no

In [75]:
import numpy as np
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.unique(arr, return_index=True,return_counts=True)


In [81]:
a=np.array([20,30,40,20,30,10,40,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([5, 0, 1, 2, 7], dtype=int64),
 array([1, 2, 2, 2, 1], dtype=int64))

# horizontal and vertical stacking

In [82]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [83]:
b

array([5, 6, 7, 8])

In [86]:
np.hstack((a,b)) # add elements of matrix horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
np.vstack((a,b))# add elements of matrix vertical

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])