In [1]:
#introduction to NUMPY ===>
#why numpy is better then list ?
#1. same data type == array
#2. memory consume ==> numpy less list more
#3. computation power ==> numpy more list less
#4. function ===> numpy high, list less

In [2]:
import numpy as np

In [3]:
a=[1,2,34]
type(a)

list

In [4]:
b=np.array(a)
type(b)

numpy.ndarray

In [12]:
no=int(input("enter no of elemnts"))
mylist=[]
for i in range(no):
    val=int(input("enter no"))
    mylist.append(val)

b=np.array(mylist)
print(b)

                  




enter no of elemnts 5
enter no 9
enter no 8
enter no 26
enter no 5
enter no 5


[ 9  8 26  5  5]


# how to check shape and size of array


In [13]:
#shape=n(rows), n(coloumn)
#size=total_elemenst ===> n(rows)*n(coloumns)

In [15]:
print("total shape==" , b.shape)
print("total size==", b.size)

total shape== (5,)
total size== 5


In [17]:
a=[[1,2,3],[2,3,4]]
b=np.array(a)
print(b)
print("shape", b.shape)
print("size",b.size)

[[1 2 3]
 [2 3 4]]
shape (2, 3)
size 6


In [18]:
a=[[1,2,3],[3,4,5],[4,3,2]]
b=np.array(a)
print(b)
print(b.shape)
print(b.size)

[[1 2 3]
 [3 4 5]
 [4 3 2]]
(3, 3)
9


In [19]:
#image ====> pixel ====> (0,250)px ====> 0px(black) , 255px(white)
#convert ===> grayscale image===>
#image (pixels)==> Normalization(0-1) ===> 0px==> black ,1px===> white 

#0,1====> neuron system
#matrix===> rows and columns
#symmetric matrix =  no of rows and column
# asymmetric matrix = no of rows and column are not equal
#diagonal matrix=diagonal elmensts only in matrix


# 1) zeros() ===> it will create a array in which all elemensta are zero

In [20]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [21]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 2)  ones() ====> it will create a array in which all elements are one 

In [23]:
a=np.ones(3)
a

array([1., 1., 1.])

In [24]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 3) eye()==> this function will create an array in which diagonal elements are 1 and other are zero

In [29]:
a=np.eye(3,4) #asymmetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
a=np.eye(4)#symmetric 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])